"""empty message

Revision ID: 8eab62885931
Revises: 4f4cc74aa77d
Create Date: 2021-03-28 22:15:24.036167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eab62885931'
down_revision = '4f4cc74aa77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('authorization_id', sa.String(length=255), nullable=True),
    sa.Column('payment_url', sa.String(length=255), nullable=True),
    sa.Column('qrcode', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column('purchases', sa.Column('payment_uuid', sa.Integer(), nullable=True))
    op.drop_column('purchases', 'type_card')
    op.drop_column('purchases', 'cpf_owner_card')
    op.drop_column('purchases', 'validity_card')
    op.drop_column('purchases', 'cvv')
    op.drop_column('purchases', 'name_owner_card')
    op.drop_column('purchases', 'number_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('number_card', sa.VARCHAR(length=255), nullable=True))
    op.add_column('purchases', sa.Column('name_owner_card', sa.VARCHAR(length=255), nullable=True))
    op.add_column('purchases', sa.Column('cvv', sa.VARCHAR(length=3), nullable=True))
    op.add_column('purchases', sa.Column('validity_card', sa.VARCHAR(length=255), nullable=True))
    op.add_column('purchases', sa.Column('cpf_owner_card', sa.VARCHAR(length=255), nullable=True))
    op.add_column('purchases', sa.Column('type_card', sa.VARCHAR(length=6), nullable=True))
    op.drop_column('purchases', 'payment_uuid')
    op.drop_table('payments')
    # ### end Alembic commands ###
