"""Initial migration.

Revision ID: eeb328b2a8cf
Revises: 
Create Date: 2020-11-17 18:08:21.531999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb328b2a8cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('type_', sa.Enum('item', 'account', 'gold', name='announcementtypeenum'), nullable=True),
    sa.Column('salesman_uuid', sa.Integer(), nullable=True),
    sa.Column('game', sa.String(length=255), nullable=True),
    sa.Column('server', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('purchases',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('initiated', 'paid', 'delivered', 'finished', name='purchasestatusenum'), nullable=True),
    sa.Column('announcement_uuid', sa.Integer(), nullable=True),
    sa.Column('type_card', sa.Enum('credit', 'debit', name='typecard'), nullable=True),
    sa.Column('number_card', sa.String(length=255), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.Column('cpf_owner_card', sa.String(length=255), nullable=True),
    sa.Column('validity_card', sa.String(length=255), nullable=True),
    sa.Column('name_owner_card', sa.String(length=255), nullable=True),
    sa.Column('salesman_uuid', sa.Integer(), nullable=True),
    sa.Column('buyer_uuid', sa.Integer(), nullable=True),
    sa.Column('nick_game', sa.String(length=255), nullable=True),
    sa.Column('salesman_delivery_confirmation', sa.Boolean(), nullable=False),
    sa.Column('buyer_delivery_confirmation', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=255), nullable=False),
    sa.Column('isSalesman', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('purchases')
    op.drop_table('announcements')
    # ### end Alembic commands ###
